//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GinClientApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GinClientApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the repository browser.
        /// </summary>
        internal static string CreateNewRepoDlg_Open_the_repository_browser {
            get {
                return ResourceManager.GetString("CreateNewRepoDlg_Open_the_repository_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string GetUserCredentials_Login_Failed {
            get {
                return ResourceManager.GetString("GetUserCredentials_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login unsuccessful. Username or password are incorrect.
        /// </summary>
        internal static string GetUserCredentials_Login_Unsuccessful {
            get {
                return ResourceManager.GetString("GetUserCredentials_Login_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered Username/Password combination is invalid.
        /// </summary>
        internal static string GetUserCredentials_The_entered_Username_Password_combination_is_invalid {
            get {
                return ResourceManager.GetString("GetUserCredentials_The_entered_Username_Password_combination_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon gin_icon {
            get {
                object obj = ResourceManager.GetObject("gin_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon gin_icon_desaturated {
            get {
                object obj = ResourceManager.GetObject("gin_icon_desaturated", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gin_icon_desaturated1 {
            get {
                object obj = ResourceManager.GetObject("gin_icon_desaturated1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string GinApplicationContext_About {
            get {
                return ResourceManager.GetString("GinApplicationContext_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to access Gin Client Service.
        /// </summary>
        internal static string GinApplicationContext_Error_while_trying_to_access_Gin_Client_Service {
            get {
                return ResourceManager.GetString("GinApplicationContext_Error_while_trying_to_access_Gin_Client_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to log in to GIN.
        /// </summary>
        internal static string GinApplicationContext_Error_while_trying_to_log_in_to_GIN {
            get {
                return ResourceManager.GetString("GinApplicationContext_Error_while_trying_to_log_in_to_GIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string GinApplicationContext_Exit {
            get {
                return ResourceManager.GetString("GinApplicationContext_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving {0} from repository {1}.
        /// </summary>
        internal static string GinApplicationContext_FileOperation_Retrieving {
            get {
                return ResourceManager.GetString("GinApplicationContext_FileOperation_Retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gin Client Error.
        /// </summary>
        internal static string GinApplicationContext_Gin_Client_Error {
            get {
                return ResourceManager.GetString("GinApplicationContext_Gin_Client_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gin Service Error.
        /// </summary>
        internal static string GinApplicationContext_Gin_Service_Error {
            get {
                return ResourceManager.GetString("GinApplicationContext_Gin_Service_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gin Service has stopped communicating..
        /// </summary>
        internal static string GinApplicationContext_Gin_Service_has_stopped_communicating_ {
            get {
                return ResourceManager.GetString("GinApplicationContext_Gin_Service_has_stopped_communicating_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Repositories.
        /// </summary>
        internal static string GinApplicationContext_Manage_Repositories {
            get {
                return ResourceManager.GetString("GinApplicationContext_Manage_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount.
        /// </summary>
        internal static string GinApplicationContext_Mount {
            get {
                return ResourceManager.GetString("GinApplicationContext_Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string GinApplicationContext_Options {
            get {
                return ResourceManager.GetString("GinApplicationContext_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIN Repository activity in progress.
        /// </summary>
        internal static string GinApplicationContext_Repository_Activity {
            get {
                return ResourceManager.GetString("GinApplicationContext_Repository_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmount.
        /// </summary>
        internal static string GinApplicationContext_Unmount {
            get {
                return ResourceManager.GetString("GinApplicationContext_Unmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string GinApplicationContext_Update {
            get {
                return ResourceManager.GetString("GinApplicationContext_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload local files.
        /// </summary>
        internal static string GinApplicationContext_Upload {
            get {
                return ResourceManager.GetString("GinApplicationContext_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gin Client Warning.
        /// </summary>
        internal static string GinClientApp_Gin_Client_Warning {
            get {
                return ResourceManager.GetString("GinClientApp_Gin_Client_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD 3-Clause License
        ///
        ///Copyright (c) 2017, German Neuroinformatics Node (G-Node)
        ///                    
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met:
        ///
        ///* Redistributions of source code must retain the above copyright notice, this
        ///  list of conditions and the following disclaimer.
        ///
        ///* Redistributions in binary form must reproduce the above copyright notice,
        ///  this list of conditions  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a directory for the checkout.
        /// </summary>
        internal static string MetroCreateNewRepoDlg_Choose_a_directory_for_the_checkout {
            get {
                return ResourceManager.GetString("MetroCreateNewRepoDlg_Choose_a_directory_for_the_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a directory for the mountpoint.
        /// </summary>
        internal static string MetroCreateNewRepoDlg_Choose_a_directory_for_the_mountpoint {
            get {
                return ResourceManager.GetString("MetroCreateNewRepoDlg_Choose_a_directory_for_the_mountpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;username&gt;/&lt;repository&gt;.
        /// </summary>
        internal static string Options__username___repository_ {
            get {
                return ResourceManager.GetString("Options__username___repository_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No checkout address has been entered..
        /// </summary>
        internal static string Options_CheckSanity_No_checkout_address_has_been_entered_ {
            get {
                return ResourceManager.GetString("Options_CheckSanity_No_checkout_address_has_been_entered_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkout address is not properly formatted. Do you wish to create a new repository with the name {0} instead?.
        /// </summary>
        internal static string Options_CheckSanity_The_checkout_address_is_not_properly_formatted {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_checkout_address_is_not_properly_formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checkout directory already exists. Do you wish to delete it?.
        /// </summary>
        internal static string Options_CheckSanity_The_checkout_directory_already_exists {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_checkout_directory_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mountpoint and checkout directory can not be subdirectories of each other..
        /// </summary>
        internal static string Options_CheckSanity_The_mountpoint_and_checkout_directory_can_not_be_subdirectories {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_mountpoint_and_checkout_directory_can_not_be_subdirectori" +
                        "es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mountpoint directory already exists. Do you wish to delete it?.
        /// </summary>
        internal static string Options_CheckSanity_The_mountpoint_directory_already_exists {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_mountpoint_directory_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the repository {0} and all associated data. Do you wish to continue?.
        /// </summary>
        internal static string Options_This_will_delete_the_repository {
            get {
                return ResourceManager.GetString("Options_This_will_delete_the_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the selected Repository and all associated data. Continue?.
        /// </summary>
        internal static string RepoManagement_Delete_repository {
            get {
                return ResourceManager.GetString("RepoManagement_Delete_repository", resourceCulture);
            }
        }
    }
}
